/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package rentcarproject.view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import rentcarproject.controller.AluguelDAO;
import rentcarproject.database.Connect;
import rentcarproject.models.Aluguel;

/**
 *
 * @author vinicius
 */
public class TelaConsultaLoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultaLoc1
     */
    public TelaConsultaLoc() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableLocacao.getModel();
        jTableLocacao.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLocacao = new javax.swing.JTable();
        jButtonExcluir5 = new javax.swing.JButton();
        jButtonCad5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        jLabel4.setText("LOCAÇÕES");

        jTableLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Modelo", "Placa", "Data Locacao", "Data de Entrega", "Valor a pagar (R$)", "Metodo Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLocacaojTableLocacaoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableLocacao);

        jButtonExcluir5.setBackground(new java.awt.Color(0, 0, 0));
        jButtonExcluir5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir5.setText("EXCLUIR");
        jButtonExcluir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluir5jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCad5.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCad5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCad5.setText("PAGO");
        jButtonCad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCad5ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonExcluir5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCad5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCad5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLocacaojTableLocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLocacaojTableLocacaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLocacaojTableLocacaoMouseClicked

    private void jButtonExcluir5jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluir5jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if(jTableLocacao.getSelectedRow() != -1){

            Aluguel aluguel = new Aluguel();
            AluguelDAO aluguelDao = new AluguelDAO();
            Connect connect = new Connect();

            String placa = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 3).toString();

            aluguel.setId(Integer.parseInt(jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 0).toString()));

            aluguelDao.delete(aluguel);

            readJTable();

            if(connect.getConnection()){
                try{

                    String sql = "UPDATE tb_veiculos SET disponibilidade_veiculo = 'DISPONIVEL' WHERE placa_veiculo = '"+placa+"'";

                    PreparedStatement statement = connect.connection.prepareStatement(sql);
                    ResultSet resultSet = statement.executeQuery();

                    resultSet.close();
                    statement.close();
                    connect.close();

                }catch(SQLException erro){
                    System.out.println(erro.toString());
                }
            }else{
                System.out.println("Erro ao conectar");
            }

        }
        
    }//GEN-LAST:event_jButtonExcluir5jButtonExcluirActionPerformed

    private void jButtonCad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCad5ActionPerformed
        // TODO add your handling code here:
        
        if(jTableLocacao.getSelectedRow() != -1){

            Aluguel aluguel = new Aluguel();
            AluguelDAO aluguelDao = new AluguelDAO();
            Connect connect = new Connect();

            String placa = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 3).toString();

            aluguel.setId(Integer.parseInt(jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 0).toString()));

            aluguelDao.delete(aluguel);

            readJTable();

            if(connect.getConnection()){
                try{

                    String sql = "UPDATE tb_veiculos SET disponibilidade_veiculo = 'DISPONIVEL' WHERE placa_veiculo = '"+placa+"'";

                    PreparedStatement statement = connect.connection.prepareStatement(sql);
                    ResultSet resultSet = statement.executeQuery();

                    resultSet.close();
                    statement.close();
                    connect.close();

                }catch(SQLException erro){
                    System.out.println(erro.toString());
                }
            }else{
                System.out.println("Erro ao conectar");
            }

        }
        
    }//GEN-LAST:event_jButtonCad5ActionPerformed

    public void readJTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTableLocacao.getModel();
        modelo.setNumRows(0);
        AluguelDAO aluguelDao = new AluguelDAO();
        
        for(Aluguel aluguel: aluguelDao.read()){
            modelo.addRow(new Object[]{
                aluguel.getId(),
                aluguel.cliente.getCpf(),
                aluguel.veiculo.getModelo(),
                aluguel.veiculo.getPlaca(),
                aluguel.getData(),
                aluguel.getDataentrega(),
                aluguel.getValor(),
                aluguel.getMetodoPag()
            });
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCad5;
    private javax.swing.JButton jButtonExcluir5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableLocacao;
    // End of variables declaration//GEN-END:variables
}
